### ISSUE TITLE
В компоненте MyMessages djpvj;yj ошибка в названии атрибута

### ISSUE THREAD

**Issue by a-potap** [visionp/yii2-private-messages#3]
в методе getAllUsers надо иправить запрос
$sql = "select usr.id, usr.$this->attributeNameUser as username, msg.cnt as cnt_mess ";
на 
$sql = "select usr.id, usr.$this->attributeNameUser as $this->attributeNameUser, msg.cnt as cnt_mess ";

**Comment by visionp** [comment]
Спасибо. Исправил.
