### ISSUE TITLE
Проблемы с установкой

### ISSUE THREAD

**Issue by Oreolek** [visionp/yii2-private-messages#5]
После установки ругается:

`The file or directory to be published does not exist: <...путь к проекту...>/vendor/bower/tinyscrollbar`

**Comment by visionp** [comment]
Исправлено.
Изменил имя папки TinyScrollbar в ресурсах.

**Comment by Oreolek** [comment]
Да, но в папке bower вообще нет ни `TinyScrollbar`, ни `tinyscrollbar`. Как её создать?

**Comment by visionp** [comment]
А как вы установили приложение?
Эта папка должна подтянуться так как эта зависимость  указана в композере.

7 Янв 2016 г. 11:53 пользователь "Alexander Yakovlev" <
notifications@github.com> написал:

**Comment by Oreolek** [comment]
Да, и она подтянулась как `vendor/bower/bower-asset/tinyscrollbar`

**Comment by visionp** [comment]
Очень странно, так как в сторонний проект подтянул для проверки и все
выглядит так http://prntscr.com/9n3hoy
А в целом чтобы исправить ситуацию нужно в
файле vendor\vision\yii2-private-messages\assets\TinyscrollbarAsset.php
указать правильное расположение папки.

2016-01-07 12:05 GMT+02:00 Alexander Yakovlev notifications@github.com:
