### ISSUE TITLE
Проблема при установке

### ISSUE THREAD

**Issue by jb-studio** [visionp/yii2-private-messages#6]
Здравствуйте!
Подскажите пожалуйста как пофиксить это?
auth_assignment' doesn't exist
В миграциях не было этой таблицы

**Comment by visionp** [comment]
Здравствуйте!
auth_assignment это таблица использующаяся для хранения ролей в БД.
Подозреваю что в конфиге указали фишку чтобы писать можно было только
администраторам, уберите это, или установите  'admins' =>false .
                //не обязательно
                //можно указать роли и/или id пользователей которые будут
видны в списке контактов всем кто не подпадает
                //в эту выборку, при этом указанные пользователи будут и
смогут писать всем зарегестрированным пользователям
            'admins' => ['admin', 7],

19 января 2016 г., 10:40 пользователь jb-studio notifications@github.com
написал:
