### ISSUE TITLE
PostgreSQL compatibility

### ISSUE THREAD

**Issue by Oreolek** [visionp/yii2-private-messages#7]
[eng]
MyMessages class: PostgreSQL has no FROM_UNIXTIME function. Also double quotes are for column names, not data.

[rus]
В классе MyMessages работа с датой идёт через чисто MySQL функцию FROM_UNIXTIME. PostgreSQL на этом падает. А ещё двойные кавычки у него для названий колонок, а не для данных (данные нужно писать в одинарных кавычках).

**Comment by visionp** [comment]
fixed
