### ISSUE TITLE
Не вижу сообщений и не могу отправить...

### ISSUE THREAD

**Issue by Shleif91** [visionp/yii2-private-messages#9]
Добрый день, прошу помощи... Установил Ваше приложение, настроил все исходя из мануала и предыдущих вопросов, но не отправляются сообщения и не отображается созданное мной в ручную в БД сообщение. Что может служить этому причиной ума не приложу. GET запросы c 500 статусом

**Comment by visionp** [comment]
Добрый день!
А в конфиге установлен nameController?

'components' => [...
        'mymessages' => [
                //Обязательно
            'class'    => 'vision\messages\components\MyMessages',
                //не обязательно
                //класс модели пользователей
                //по-умолчанию \Yii::$app->user->identityClass
            'modelUser' => 'common\models\User',
                //имя контроллера где разместили action
            'nameController' => ’Site'
    ...]

**Comment by Shleif91** [comment]
Да, конфиг полностью ваш, только в 'admins' => false. У меня advanced, конфиг и в frontend пихал и в common - результат одинаковый. nameController пробовал и Site и site

**Comment by Shleif91** [comment]
Написал 'site' с маленькой. Конфиг находиться в frontend, сделал чпу - всё заработало! Большое спасибо, что ответили!

**Comment by Shleif91** [comment]
Помогите ещё в одной поблеме: правлю web\css\cload_message.css но результатов правки не видно... Вижу что при выводе страницы используется файл css из frontend\web\assets\"цифрыбуквы"\css\cload_message.css, правлю его - никаких результатов
